USE innovations4austria;
GO

CREATE TABLE portalusers(
	id INT IDENTITY NOT NULL,
	firstname NVARCHAR(50) NOT NULL,
	lastname NVARCHAR(50) NOT NULL,
	email NVARCHAR(250) NOT NULL,
	[password] VARBINARY(1000) NOT NULL,
	role_id INT NOT NULL,
	company_id INT NOT NULL
);
GO

CREATE TABLE roles(
	id INT IDENTITY NOT NULL,
	[description] NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE companies(
	id INT IDENTITY NOT NULL,
	name NVARCHAR(50) NOT NULL,
	zip NVARCHAR(10) NOT NULL,
	city NVARCHAR(50) NOT NULL,
	street NVARCHAR(50) NOT NULL,
	number NVARCHAR(10) NOT NULL
);
GO

CREATE TABLE rooms(
	id INT IDENTITY NOT NULL,
	[description] NVARCHAR(50) NOT NULL,
	facility_id INT NOT NULL
);
GO

CREATE TABLE facilities(
	id INT IDENTITY NOT NULL,
	name NVARCHAR(50) NOT NULL,
	zip NVARCHAR(10) NOT NULL,
	city NVARCHAR(50) NOT NULL,
	street NVARCHAR(50) NOT NULL,
	number NVARCHAR(10) NOT NULL
);
GO

CREATE TABLE furnishments(
	id INT IDENTITY NOT NULL,
	[description] NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE roomfurnishments(
	id INT IDENTITY NOT NULL,
	furnishment_id INT NOT NULL,
	room_id INT NOT NULL
);
GO

CREATE TABLE bookings(
	id INT IDENTITY NOT NULL,
	portaluser_id INT NOT NULL,
	room_id INT NOT NULL,
	company_id INT NOT NULL,
	createdate DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE bookingdetails(
	id INT IDENTITY NOT NULL,
	[from] DATE NOT NULL,
	[to] DATE NOT NULL,
	price DECIMAL(6,2) NOT NULL,
	booking_id INT NOT NULL,
	createdate DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE bills(
	id INT IDENTITY NOT NULL,
	company_id INT NOT NULL,
	billdate DATETIME NOT NULL,
	portaluser_id INT NOT NULL,
	createdate DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE billdetails(
	id INT IDENTITY NOT NULL,
	bill_id INT NOT NULL,
	booking_id INT NOT NULL,
	value DECIMAL(6,2),
	createdate DATETIME NOT NULL DEFAULT GETDATE()
);
GO

CREATE TABLE logs(
	id INT IDENTITY NOT NULL,
	portaluser_id INT NOT NULL,
	[table] NVARCHAR(50) NOT NULL,
	old_value NVARCHAR(50),
	new_value NVARCHAR(50),
	createdate DATETIME NOT NULL DEFAULT GETDATE()
);
GO