//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class billdetail
    {
        public int id { get; set; }
        public int bill_id { get; set; }
        public int bookingdetail_id { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual bookingdetail bookingdetail { get; set; }
    }
}
