//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingdetail
    {
        public int id { get; set; }
        public int booking_id { get; set; }
        public Nullable<int> bill_id { get; set; }
        public System.DateTime booking_date { get; set; }
        public decimal price { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual booking booking { get; set; }
    }
}
