//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public int id { get; set; }
        public int facility_id { get; set; }
        public int company_id { get; set; }
        public int percentage { get; set; }
    
        public virtual company company { get; set; }
        public virtual facility facility { get; set; }
    }
}
