//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.dataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class innovations4austriaEntities : DbContext
    {
        public innovations4austriaEntities()
            : base("name=innovations4austriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<bookingdetail> bookingdetails { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<facility> facilities { get; set; }
        public virtual DbSet<furnishment> furnishments { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<portaluser> portalusers { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<roomfurnishment> roomfurnishments { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<image> images { get; set; }
    
        public virtual ObjectResult<sp_getFilteredRoomsByDate_Result> sp_getFilteredRoomsByDate(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getFilteredRoomsByDate_Result>("sp_getFilteredRoomsByDate", startParameter, endParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getFilteredRoomIds(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getFilteredRoomIds", startParameter, endParameter);
        }
    }
}
