//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.dataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class innovations4austriaEntities : DbContext
    {
        public innovations4austriaEntities()
            : base("name=innovations4austriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<bookingdetail> bookingdetails { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<facility> facilities { get; set; }
        public virtual DbSet<furnishment> furnishments { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<portaluser> portalusers { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<roomfurnishment> roomfurnishments { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<discount> discounts { get; set; }
    
        public virtual ObjectResult<sp_getFilteredRoomsByDate_Result> sp_getFilteredRoomsByDate(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getFilteredRoomsByDate_Result>("sp_getFilteredRoomsByDate", startParameter, endParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getFilteredRoomIds(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getFilteredRoomIds", startParameter, endParameter);
        }
    
        public virtual int sp_UpdateRoom(Nullable<int> id, string description, Nullable<int> facility_id, Nullable<decimal> price)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var facility_idParameter = facility_id.HasValue ?
                new ObjectParameter("facility_id", facility_id) :
                new ObjectParameter("facility_id", typeof(int));
    
            var priceParameter = price.HasValue ?
                new ObjectParameter("price", price) :
                new ObjectParameter("price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateRoom", idParameter, descriptionParameter, facility_idParameter, priceParameter);
        }
    
        public virtual int sp_UpdateRoomfurnishments(Nullable<int> id, Nullable<int> oldFurnishment, Nullable<int> newFurnishment)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var oldFurnishmentParameter = oldFurnishment.HasValue ?
                new ObjectParameter("oldFurnishment", oldFurnishment) :
                new ObjectParameter("oldFurnishment", typeof(int));
    
            var newFurnishmentParameter = newFurnishment.HasValue ?
                new ObjectParameter("newFurnishment", newFurnishment) :
                new ObjectParameter("newFurnishment", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateRoomfurnishments", idParameter, oldFurnishmentParameter, newFurnishmentParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_getRoomIdsBetweenDates(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_getRoomIdsBetweenDates", startParameter, endParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_GetExpendituresByMonthAndCompany(Nullable<int> companyId, Nullable<int> month, Nullable<int> year)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_GetExpendituresByMonthAndCompany", companyIdParameter, monthParameter, yearParameter);
        }
    }
}
