//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovation4austria.dataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class innovations4austriaEntities : DbContext
    {
        public innovations4austriaEntities()
            : base("name=innovations4austriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<bookingdetail> bookingdetails { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<facility> facilities { get; set; }
        public virtual DbSet<furnishment> furnishments { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<portaluser> portalusers { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<roomfurnishment> roomfurnishments { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<image> images { get; set; }
    }
}
