//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovations4austria.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class billdetail
    {
        public int id { get; set; }
        public int bill_id { get; set; }
        public int bookingdetail_id { get; set; }
    
        public virtual bill bill { get; set; }
        public virtual bookingdetail bookingdetail { get; set; }
    }
}
