//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovations4austria.logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class innovations4austriaEntities : DbContext
    {
        public innovations4austriaEntities()
            : base("name=innovations4austriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<billdetail> billdetails { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<bookingdetail> bookingdetails { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<facility> facilities { get; set; }
        public virtual DbSet<furnishment> furnishments { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<portaluser> portalusers { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<roomfurnishment> roomfurnishments { get; set; }
        public virtual DbSet<room> rooms { get; set; }
    }
}
