//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovations4austria.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class portaluser
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public byte[] password { get; set; }
        public int role_id { get; set; }
        public int company_id { get; set; }
    
        public virtual company company { get; set; }
        public virtual role role { get; set; }
    }
}
