//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace innovations4austria.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomfurnishment
    {
        public int id { get; set; }
        public int furnishment_id { get; set; }
        public int room_id { get; set; }
    
        public virtual furnishment furnishment { get; set; }
        public virtual room room { get; set; }
    }
}
